import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconBox,
  IconBrandDocker,
  IconBrandGithub,
  IconBrandUbuntu,
  IconBrightness,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClock,
  IconClockHour4,
  IconCode,
  IconCommand,
  IconCopy,
  IconCpu,
  IconDatabase,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileUpload,
  IconFolder,
  IconFolderOpen,
  IconGlobe,
  IconGripVertical,
  IconHelpCircle,
  IconInfoCircle,
  IconKey,
  IconLayoutDashboard,
  IconLayoutSidebar,
  IconList,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMinus,
  IconMoon,
  IconNetwork,
  IconPalette,
  IconPlus,
  IconProps,
  IconRefresh,
  IconReportAnalytics,
  IconSearch,
  IconSelector,
  IconServer,
  IconServerBolt,
  IconSettings,
  IconShare,
  IconShield,
  IconShieldLock,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconPin,
  IconLayoutColumns,
  IconPinFilled,
  IconSun,
  IconTerminal2,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUsers,
  IconWorld,
  IconX,
  IconCertificate,
  IconFlame,
  IconActivity,
  IconPlayerPlay,
  IconPlayerStop,
  IconPower,
  IconRocket,
  IconCloudUpload,
  IconWifi,
  IconDeviceDesktop,
  IconBrandDebian,
  IconGauge,
  IconArrowDown,
  IconArrowUp,
  IconDeviceSdCard,
  IconDeviceDesktopAnalytics
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  clockHour: IconClockHour4,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  refresh: IconRefresh,
  activity: IconActivity,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  account: IconUserCircle,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  logo: IconCommand,
  docker: IconBrandDocker,
  ubuntu: IconBrandUbuntu,
  debian: IconBrandDebian,

  // Communication
  notification: IconBell,
  chat: IconMessage,

  // Files
  page: IconFile,
  post: IconFileText,
  folder: IconFolder,
  folderOpen: IconFolderOpen,
  fileUpload: IconFileUpload,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,
  copy: IconCopy,
  download: IconDownload,
  play: IconPlayerPlay,
  stop: IconPlayerStop,
  power: IconPower,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Data / Charts
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eye: IconEye,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,

  // Server / VPS Management
  server: IconServer,
  serverBolt: IconServerBolt,
  cpu: IconCpu,
  database: IconDatabase,
  terminal: IconTerminal2,
  globe: IconGlobe,
  network: IconNetwork,
  world: IconWorld,
  shield: IconShield,
  shieldLock: IconShieldLock,
  key: IconKey,
  certificate: IconCertificate,
  flame: IconFlame,
  lock: IconLock,
  rocket: IconRocket,
  cloudUpload: IconCloudUpload,
  wifi: IconWifi,
  desktop: IconDeviceDesktop,

  // System monitoring
  gauge: IconGauge,
  arrowDown: IconArrowDown,
  arrowUp: IconArrowUp,
  sdCard: IconDeviceSdCard,
  systemMonitor: IconDeviceDesktopAnalytics,

  // Misc
  sparkles: IconSparkles,
  star: IconStar,
  pin: IconPin,
  splitPane: IconLayoutColumns,
  pinFilled: IconPinFilled,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots,
  logs: IconReportAnalytics,
  list: IconList,
  box: IconBox
};
